name: Publish CUPS Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'etc-cups/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (Ubuntu)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: BASE_DISTRO=ubuntu:jammy
          tags: |
            xjasonlyu/cups:latest
            xjasonlyu/cups:ubuntu
            ghcr.io/xjasonlyu/cups:latest
            ghcr.io/xjasonlyu/cups:ubuntu

      - name: Build and Push (Debian)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: BASE_DISTRO=debian:bullseye-slim
          tags: |
            xjasonlyu/cups:debian
            ghcr.io/xjasonlyu/cups:debian
